### ISSUE TITLE
rgkit integration

### ISSUE THREAD

**Issue by ghost** [ramk13/robotgame#2]
Hi ramk13, what do you think about rgkit integration for some of your tools? It can either be integrated directly into rgkit with pull requests from you for whichever parts you'd like or we can link to your repo from rgkit.

The former will get more usage of your tools whereas the latter provides more ownership. Whatever you prefer I'm fine with, but I'd like more people to have access to your tools and strategies, even if it's just a better link in the README. :)

**Comment by ramk13** [comment]
Pull requests sounds fine to me. More people using learning and coding bots is more fun for all of us. Is it ok if I leave an edited credit in place that says something like 'Originally written by ramk13' since other people will eventually contribute? Of course if someone else does a major rewrite the credit could be removed.

What stuff should I submit a pull request for and where should it be put in rgkit? I guess the guide would fall under documentation. Would you also create a sample bot folder? Let me know and we'll figure it out.

I know I stopped work on the strategy guide, but I'll pick it back up sometime soon. Work is a little busy at the moment, plus I still want to spend time coding bots. I was planning to write the intermediate guide that would lead to simplebot. Then maybe an 'advanced' guide that introduces the idea of heuristics. Might be a while before I get that far though.

**Comment by ghost** [comment]
I'm fine with whatever attribution you want to add. I'm glad you're open to the idea of having others also contribute and use your guides.

A sample bot folder would make sense. I think we have a couple for testing but they could probably be organized better. Try for something you think makes sense and we can discuss in a PR. Please make PRs and decisions on your own schedule and what you feel seems right. Take your time, no hurry. I think whatever you decide will probably be correct.

Looking forward to more guides when you get more time! :)
